---
- name: deploy web servers
  hosts: web_servers
  remote_user: root
  become: true
  tasks:
    - name: install apache
      apt:
         name: apache2
         state: present
    - name: run service
      service:
             name: apache2
             state: started
    - name: copy web content
      copy:
          src: /home/ubuntu/index.html
          dest: /var/www/html/
...
